### ISSUE TITLE
Inside the button row, add col-3's for our buttons

### ISSUE THREAD

**Issue by Ckopei** [rgoderis/event-project#26]
Inside the row we made for out buttons, under the parallax container, make four columns (use classes "col s3") to hold our buttons.

**Comment by dlopez079** [comment]
This will not work for the buttons.  It looks like the columns do not divide like they do in bootstrap.  I check for the features of a form in Materialize and I didn't see anything similar to Bootstrap.  The buttons are created with <a> tags.  I removed the <div> tags and left the <a> tags inside the "buttonsRow".
